[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
proxy_mode = True
list_db = True
admin_passwd = $pbkdf2-sha512$600000$AmAMAcCYk1KqtTYmZMx5jw$nBoUH7YF8IAt2RC26..OeMnIEm.k8dE8oRgqzw8c5ZDou/OkEEmfrRe7GNar7C5ZVCevbnsx6oePBJUZrB6BbQ

