[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
proxy_mode = True
list_db = True
admin_passwd = $pbkdf2-sha512$600000$Y6yVUorxvtfaG4MwJiTkPA$DX5dZJdPmwQztZQELbJ2.WsNa5j96iMQVoo2rT3tvUYFO60qoo2U8VYy2C.g5ZTcOQcKqyYEiqwNrFIMmLUSsA
dbfilter = .*
