{
    "name": "Inca's Paradise Reservas",
    "summary": "Gestión interna de cotizaciones, reservas y pasajeros",
    "version": "19.0.1.0.0",
    "category": "Inca's Paradise",
    "author": "Inca's Paradise",
    "license": "LGPL-3",
    "depends": ["incas_core"],
    "data": [
        "security/ir.model.access.csv",
        "security/incas_catalogo_access.xml",
        "data/incas_reservas_sequence.xml",
        "data/incas_currency_rate_cron.xml",
        "reports/incas_reservas_reports.xml",
        "views/incas_servicio_catalogo_views.xml",
        "views/incas_hotel_views.xml",
        "views/incas_extra_views.xml",
        "views/incas_catalogo_tour_views.xml",
        "views/incas_catalogo_transporte_views.xml",
        "views/incas_currency_rate_views.xml",
        "views/incas_cotizacion_views.xml",
        "views/incas_reserva_views.xml",
        "views/incas_pago_views.xml",
        "views/incas_pasajero_views.xml",
    ],
    "application": False,
    "installable": True,
}
